resources:
  pipelines:
  - pipeline: haibun
    source: withhaibun.haibun
    trigger: true

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    mkdir test
    HAIBUN_O_WEB_PLAYWRIGHT_HEADLESS=true HAIBUN_OUTPUTAsJUnit HAIBUN_OUTPUT_LOCATION=test/ npm run test
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test/**.xml'