
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    npm run test
    mkdir test
    echo '<?xml version="1.0"?> <testsuites tests="1" name="Haibun-Junit" failures="0"> <testsuite name="Haibun-Junit-Suite" tests="1" skipped="0" failures="0"> <testcase name="/features/upload-verify.feature" id="/features/upload-verify.feature"/> </testsuite> </testsuites>' \
 > test/0-result.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: 'test/**.xml'