resources:
  pipelines:
  - pipeline: haibun
    source: withhaibun.haibun
    trigger: true

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    mkdir test
    HAIBUN_OUTPUT_DEST=test/result.xml HAIBUN_OUTPUT=~@haibun/out-xunit/build/out-xunit HAIBUN_O_WEB_PLAYWRIGHT_HEADLESS=true npm run test
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test/**.xml'
