# Codeceptjs based BDD testing

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

resources:
 pipelines:
   - pipeline: bdd-pipeline-test
     source: sign-in-canada.azure-lab-pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'


- script: |
    CI=true npm run test-junit
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: output/bdd-test-results.xml

- script: |
   ls output
