name: "Haibun e2e tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.haibun-e2e-action }}

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: playwright install
        run: |
          npx playwright install-deps
          npx playwright install
        
      - name: Build
        run: npm run build

      - name: Run tests
        continue-on-error: true
        run: npm test a11y

      - name: Publish
        run: npm run publish

      - name: Add reviews
        run: git add ./reviews/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update e2e test reviews"
